nameOverride: sd-creation-wizard-api
fullnameOverride: sd-creation-wizard-api
common:
  labels:
    standard:
      app.kubernetes.io/version: v0.0.1
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: sd-creation-wizard
serviceAccount:
  create: true
ingresses:
  default:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    port: 80
    hosts:
      "sd-creation-wizard.EXAMPLE.ORG": /api(/|$)(.*)
    tls:
      - secretName: wildcard-EXAMPLE-ORG
        hosts:
          - sd-creation-wizard.EXAMPLE.ORG
service:
  enabled: true
  type: ClusterIP
  ports:
    web:
      internal: 8080
      external: 80
deployments:
  default:
    enabled: true
    replicas: 2
    revisionHistoryLimit: 10
    pdb:
      enabled: true
      minAvailable: 1
    pod:
      pullSecrets:
        - "regcred-sd-creation-wizard-api"
    affinity:
      # use of simple rule
      affinityRule: "ShouldBeOnDifferentNode"
    containers:
      - repository: registry.gitlab.com/gaia-x/data-infrastructure-federation-services/self-description-tooling/sd-creation-wizard/sd-creation-wizard-api/api
        tag: "acfce215"
        pullPolicy: Always
        probes:
          # Checks if application has finished starting - restarts the container on fail
          startupProbe:
            httpGet:
              path: /getAvailableShapes
              port: 8080
            failureThreshold: 3
            periodSeconds: 2
            initialDelaySeconds: 5
          # Checks if application is alive - restarts the container on fail
          livenessProbe:
            httpGet:
              path: /getAvailableShapes
              port: 8080
            initialDelaySeconds: 5
            failureThreshold: 3
            periodSeconds: 10
          # Checks if application is ready to serve traffic - removes it from service endpoint on fail
          readinessProbe:
            httpGet:
              path: /getAvailableShapes
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
    #  resources:
    #    requests:
    #      memory: "200Mi"
    #      cpu: "200m"
